
CREATE TABLE COMPONENT (
  ID INTEGER NOT NULL AUTO_INCREMENT,
  NAME VARCHAR(128) NOT NULL,
  VERSION VARCHAR(128) NOT NULL,  
  UNIQUE (NAME, VERSION),
  PRIMARY KEY (ID)
)ENGINE INNODB;


CREATE TABLE PRODUCT (
  ID INTEGER NOT NULL AUTO_INCREMENT,
  NAME VARCHAR(128) NOT NULL,
  VERSION VARCHAR(128) NOT NULL,
  
  URL VARCHAR(128),
  UNIQUE (NAME, VERSION),
  PRIMARY KEY (ID)
  )ENGINE INNODB;


CREATE TABLE PRODUCT_COMPONENT_ENTRY (
  ID INTEGER NOT NULL AUTO_INCREMENT,
  COMPONENT_ID INTEGER NOT NULL,
  PRODUCT_ID INTEGER NOT NULL,
  PRIMARY KEY (ID),
  UNIQUE (COMPONENT_ID, PRODUCT_ID),
  FOREIGN KEY (COMPONENT_ID) REFERENCES COMPONENT (ID),
  FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT (ID)
)ENGINE INNODB;

/**
CREATE TABLE API_COMPONENT_ENTRY (
  ID INTEGER NOT NULL AUTO_INCREMENT,
  COMPONENT_ID INTEGER NOT NULL,
  API_ID INTEGER NOT NULL,
  PRIMARY KEY (ID),
  UNIQUE (COMPONENT_ID, API_ID),
  FOREIGN KEY (COMPONENT_ID) REFERENCES COMPONENT (ID),
  FOREIGN KEY (API_ID) REFERENCES AM_API (API_ID)
)ENGINE INNODB;

CREATE TABLE API_PRODUCT_ENTRY (
  ID INTEGER NOT NULL AUTO_INCREMENT,
  PRODUCT_ID INTEGER NOT NULL,
  API_ID INTEGER NOT NULL,
  PRIMARY KEY (ID),
  UNIQUE (PRODUCT_ID, API_ID),
  FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT (ID),
  FOREIGN KEY (API_ID) REFERENCES AM_API (API_ID)
)ENGINE INNODB;

**/

/*
create database WSO2AM_DB;
GRANT ALL ON WSO2AM_DB.* TO wso2carbon@localhost IDENTIFIED BY "wso2carbon";
use apimdb;
*/


